2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_setup.py:_flush():67] Configure stats pid to 1884770
2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_setup.py:_flush():67] Loading settings from /leonardo/home/userexternal/atorresl/.config/wandb/settings
2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_setup.py:_flush():67] Loading settings from /leonardo_work/BOOST_LCustodi/script/training/nanoGPT_karpathy_temp/wandb/settings
2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /leonardo_work/BOOST_LCustodi/script/training/nanoGPT_karpathy_temp/wandb/offline-run-20250309_183058-izcemdtl/logs/debug.log
2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /leonardo_work/BOOST_LCustodi/script/training/nanoGPT_karpathy_temp/wandb/offline-run-20250309_183058-izcemdtl/logs/debug-internal.log
2025-03-09 18:30:58,163 INFO    MainThread:1884770 [wandb_init.py:init():761] calling init triggers
2025-03-09 18:30:58,164 INFO    MainThread:1884770 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'out_dir': 'logs', 'eval_interval': 125, 'log_interval': 1, 'eval_iters': 200, 'eval_only': False, 'always_save_checkpoint': True, 'init_from': 'scratch', 'wandb_log': True, 'wandb_project': 'ngpt2025', 'wandb_run_name': 'gpt2_nanogptkarpathy', 'gradient_accumulation_steps': 16, 'batch_size': 8, 'block_size': 4096, 'n_layer': 12, 'n_head': 6, 'n_embd': 768, 'dropout': 0.0, 'bias': False, 'learning_rate': 0.003, 'max_iters': 10000, 'weight_decay': 0.1, 'beta1': 0.9, 'beta2': 0.95, 'grad_clip': 1.0, 'decay_lr': True, 'warmup_iters': 2000, 'lr_decay_iters': 10000, 'min_lr': 0, 'backend': 'nccl', 'device': 'cuda', 'dtype': 'bfloat16', 'compile': True, '_wandb': {}}
2025-03-09 18:30:58,164 INFO    MainThread:1884770 [wandb_init.py:init():784] starting backend
2025-03-09 18:30:58,527 INFO    MainThread:1884770 [wandb_init.py:init():788] sending inform_init request
2025-03-09 18:30:58,548 INFO    MainThread:1884770 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-09 18:30:58,549 INFO    MainThread:1884770 [wandb_init.py:init():803] backend started and connected
2025-03-09 18:30:58,550 INFO    MainThread:1884770 [wandb_init.py:init():896] updated telemetry
2025-03-09 18:30:58,637 INFO    MainThread:1884770 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-09 18:30:59,189 INFO    MainThread:1884770 [wandb_init.py:init():995] starting run threads in backend
2025-03-09 18:31:02,079 INFO    MainThread:1884770 [wandb_run.py:_console_start():2377] atexit reg
2025-03-09 18:31:02,079 INFO    MainThread:1884770 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 18:31:02,079 INFO    MainThread:1884770 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 18:31:02,079 INFO    MainThread:1884770 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-09 18:31:02,116 INFO    MainThread:1884770 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-09 21:00:51,221 WARNING MsgRouterThr:1884770 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/leonardo_work/BOOST_LCustodi/script/training/flex_fa_training_env/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_work/BOOST_LCustodi/script/training/flex_fa_training_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_work/BOOST_LCustodi/script/training/flex_fa_training_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/leonardo_work/BOOST_LCustodi/script/training/flex_fa_training_env/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_work/BOOST_LCustodi/script/training/flex_fa_training_env/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
